### ISSUE TITLE
Add to brew 

### ISSUE THREAD

**Issue by elia** [proger/fsevent_watch#1]
```
brew install fsevent_watch
```

would be really nice to have

**Comment by Frizlab** [comment]
Can we have (at least) a tag? I wanted to create the formula for Homebrew, but I can't do it (in the core of Homebrew) if the repo does not have a tag 😞

**Comment by proger** [comment]
@Frizlab I've created https://github.com/proger/fsevent_watch/releases/tag/homebrew_release — hope this helps.

**Comment by Frizlab** [comment]
It should! I'm making the brew formula now. I'll keep you posted. Thx :)

**Comment by Frizlab** [comment]
Mmmh actually, a tag like `v1.0`, or `fsevent_watch-1.0` would be better suited for Homebrew. It detects the version from the URL of the tarball. I can force it, but the version should be chosen by you ;)

**Comment by proger** [comment]
@Frizlab I've created `v0.1`, this should help :)

**Comment by Frizlab** [comment]
Thx!
Pull request sent to Homebrew (https://github.com/Homebrew/homebrew/pull/37389)

**Comment by proger** [comment]
(closing as the package has been in brew for a while now)
