### ISSUE TITLE
Does it work on EL Capitan?

### ISSUE THREAD

**Issue by cw1nte** [proger/fsevent_watch#2]
(First contact with GitHub BTW). Made the command line tool but other than responding to version etc it never seems to show any fsevents. Is this due to Capitan security model?
(The UI fseventer app I used fine on 10.6.8 no longer works)

**Comment by proger** [comment]
Works 10.11.4 with security protection disabled:

```
~/src/fsevent_watch% sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65
~/src/fsevent_watch% csrutil status
System Integrity Protection status: disabled.

~/src/fsevent_watch% ./fsevent_watch -F . &
[1] 30342
~/src/fsevent_watch% touch Makefile
42722863    0x00010400=[inodemetamod]   /Users/vladki/src/fsevent_watch/Makefile
```

Please try to include a reproducible test case with `sw_vers` and `csrutil status` if you see the problem persist. (I.e. I need someone to confirm this is the case when system integrity protection  is on)

**Comment by cw1nte** [comment]
It was my error in how to use (the help could be little clearer?), 
in fact it is working WITH SIP ON 10.11.3:
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21

[23582:23581 722] 16:17:48 Sat Apr 02 [colinwinuser+1:1] Documents
$ csrutil status
System Integrity Protection status: enabled.

[23582:23581 723] 16:18:20 Sat Apr 02 [colinwinuser+1:1] Documents
$ fsevent_watch -F . &
[2] 34284

[23582:23581 724] 16:18:33 Sat Apr 02 [colinwinuser+2:1] Documents
$ touch testfile

$ 18158642200757136819  0x00010400=[inodemetamod]   /Users/colinwinuser/Documents/testfile
My thanks…

**Comment by proger** [comment]
Thanks for attaching the console snippet! Perhaps you tried to run it without `-F` before? It might make sense to enable this flag by default.
